[settings]
db_path = "/av/data/repos/avscheduler/jobs.db"
sampling_interval = 1000
pid_file = "/av/data/repos/avscheduler/logs/daemon.pid"

[web_server]
host = "127.0.0.1"
port = 5000

[interpreters]
PYTHON = "/usr/bin/python3"
BASH = "/bin/bash"

# Cron format:
# * * * * *
# | | | | |
# | | | | day of the week (0–6) (Sunday to Saturday;
# | | | month (1–12)             7 is also Sunday on some systems)
# | | day of the month (1–31)
# | hour (0–23)
# minute (0–59)

# Job format:
# [jobs.<job_name>]
[jobs.job_1]
type = "PYTHON"
schedule_type = "cron"
schedule = "10 * * * *"
command = "print('Hello, World!')"
env_file = "/av/data/repos/avscheduler/env_file.env"
condition = "job_2.last_run_successful and job_2.finished_within(2h)"

[jobs.job_2]
type = "BASH"
schedule_type = "interval"
interval_seconds = 3600
command = "echo 'Running Job 2'"

[jobs.loterias]
type = "BASH"
schedule_type = "cron"
schedule = "55 20 * * *"
env_file = "/av/data/loterias/env"
command = "/av/data/repos/avscheduler/utils/job_wrapper.sh /av/data/loterias/auto-update.job.sh"
